-- Load modules
reload "user.plugins"
reload "user.options"
reload "user.neovide"
reload "user.config"
reload "user.keymaps"
reload "user.auto-commands"
reload "user.lsp"
reload "user.fidget"
reload "user.cybu"
reload "user.todo-comments"
reload "user.jaq"
reload "user.icons"
reload "user.which_keys"
reload "user.snippets"
